spring:
  application:
    name:ys
server:
port: 8080


datasource:
url: jdbc:mysql://localhost:3306/ys_tb?characterEncoding=UTF-8
username: root
password: root
type: com.alibaba.druid.pool.DruidDataSource
driver-class-name: com.mysql.jdbc.Driver

jackson:
serialization:
write-dates-as-timestamps: true
default-property-inclusion: non_null


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.ys.entity
  configuration:
    mapUnderscoreToCamelCase: true
