spring:
  application:
    name: commens
  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: false


redis:
  mode: single
  address: redis://127.0.0.1:6379
  password:
  timeout: 3000
  database: 0
  pool:
    max-active: 64
    max-idle: 24
    min-idle: 8
    max-wait: 3000
logging:
  level:
    org.ys.commens.dao: debug
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.ys.commens.entity
  global-config:
    db-config:
      update-strategy: IGNORED # 或者使用 IGNORED 允许更新为 null



