spring:
  application:
    name: ys-tb
  datasource:
    url: jdbc:mysql://localhost:3306/ys_tb?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    database-name: ys_tb
    url-root: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:      #activemq-pool 依赖是为了启用连接池，这在生产环境中通常是个好主意，因为它可以提高性能
      enabled: true
    max-connections: 50
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.ys.commens.entity
  global-config:
    db-config:
      update-strategy: IGNORED # 或者使用 IGNORED 允许更新为 null
server:
  port: 8080
jackson:
  serialization:
    write-dates-as-timestamps: true
  default-property-inclusion: non_null
logging:
  level:
    org.ys.commens.dao: debug


redis:
  mode: single
  address: redis://127.0.0.1:6379
  password:
  timeout: 3000
  database: 0
  pool:
    max-active: 64
    max-idle: 24
    min-idle: 8
    max-wait: 3000



#自定义参数区域------------------------

seckill:   #秒杀配置参数
  orderTimeOut: 5 #秒杀订单过期时间
