spring:
  application:
    name: ys-tb
  datasource:
    url: jdbc:mysql://localhost:3306/ys_tb?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 8080




jackson:
  serialization:
    write-dates-as-timestamps: true
  default-property-inclusion: non_null


mybatis:
  mapper-locations: classpath:mapper/*.xml  # XML 映射文件路径
  type-aliases-package: org.ys.entity
  configuration:
    mapUnderscoreToCamelCase: true

  mybatis-plus:
    mapper-locations: classpath*:mapper/**/*.xml
    configuration:
      mapUnderscoreToCamelCase: true